# Generated by Django 4.2 on 2023-12-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attributes", "0006_upload_tags_roles_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="Описание"
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(verbose_name="Время и дата начала"),
                ),
                (
                    "is_internal",
                    models.BooleanField(verbose_name="Мероприятие внутреннее"),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("on", "Online"),
                            ("off", "Offline"),
                            ("both", "Online + Offline"),
                        ],
                        max_length=5,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Место проведения",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        verbose_name="Ссылка на страницу мероприятия",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="Комментарии"),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attributes.eventstatus",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="attributes.tag", verbose_name="Теги"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип мероприятия",
                "verbose_name_plural": "Типы мероприятий",
                "default_related_name": "events",
            },
        ),
    ]
