# Generated by Django 4.2 on 2023-12-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attributes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип мероприятия",
                "verbose_name_plural": "Типы мероприятий",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Проработка"),
                            ("conc", "Согласование"),
                            ("prep", "Подготовка"),
                            ("over", "Завершено"),
                            ("canc", "Отменено"),
                        ],
                        max_length=5,
                        verbose_name="Текущий статус",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(verbose_name="Время и дата начала"),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("on", "Online"),
                            ("off", "Offline"),
                            ("both", "Online + Offline"),
                        ],
                        max_length=5,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=255, verbose_name="Место проведения"
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        related_name="events", to="attributes.theme"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="events.eventtype",
                        verbose_name="Тип мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип мероприятия",
                "verbose_name_plural": "Типы мероприятий",
            },
        ),
    ]
