# Generated by Django 4.2 on 2023-12-15 21:56

from django.db import migrations, models

from apps.core.utils import get_event_types_datasets


def create_types(apps, schema_editor):
    EventType: models.Model = apps.get_model("events", "EventType")
    types_datasets = get_event_types_datasets()
    if types_datasets:
        types = [EventType(**fields) for fields in types_datasets]
        EventType.objects.bulk_create(types, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_types),
    ]
