# Generated by Django 4.2 on 2023-12-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_options_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registered",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Пришло на мероприятие"
            ),
        ),
    ]
