# Generated by Django 4.2 on 2023-12-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attributes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "is_colleague",
                    models.BooleanField(verbose_name="Сотрудник компании"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attributes.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attributes.grade",
                        verbose_name="Должность",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attributes.job",
                        verbose_name="Должность",
                    ),
                ),
                (
                    "tools",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specialists",
                        to="attributes.tool",
                        verbose_name="Инструменты",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
