# Generated by Django 4.2 on 2023-12-16 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0004_eventstatus_role_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Theme",
        ),
    ]
