# Generated by Django 4.2 on 2023-12-16 07:40

from django.db import migrations, models

from apps.core.utils import (
    get_tags_datasets,
    get_status_datasets,
    get_roles_datasets,
)


def create_tags(apps, schema_editor):
    Tag: models.Model = apps.get_model("attributes", "Tag")
    datasets = get_tags_datasets()
    if datasets:
        tags = [Tag(**fields) for fields in datasets]
        Tag.objects.bulk_create(tags, ignore_conflicts=True)


def create_roles(apps, schema_editor):
    Role: models.Model = apps.get_model("attributes", "Role")
    datasets = get_roles_datasets()
    if datasets:
        roles = [Role(**fields) for fields in datasets]
        Role.objects.bulk_create(roles, ignore_conflicts=True)


def create_statuses(apps, schema_editor):
    EventStatus: models.Model = apps.get_model("attributes", "EventStatus")
    datasets = get_status_datasets()
    if datasets:
        statuses = [EventStatus(**fields) for fields in datasets]
        EventStatus.objects.bulk_create(statuses, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0005_delete_theme"),
    ]

    operations = [
        migrations.RunPython(create_tags),
        migrations.RunPython(create_roles),
        migrations.RunPython(create_statuses),
    ]
